png("d:/coursera/EDA/ExData_Plotting1/plot3.png")
plot(data$dateAndTime,data$Sub_metering_1,type="l",col ="black" ,xlab="",ylab="Energy sub metering")
lines(data$dateAndTime,data$Sub_metering_2,col ="red")
lines(data$dateAndTime,data$Sub_metering_3,col ="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","blue","red"),cex=0.7)
dev.off()