png("d:/coursera/EDA/ExData_Plotting1/plot4.png")
par(mfrow=c(2,2))
plot(data$dateAndTime,data$Global_active_power,type="l",xlab="",ylab="Global Active Power")
plot(data$dateAndTime,data$Voltage,type="l",xlab="dateTime",ylab="Voltage")
plot(data$dateAndTime,data$Sub_metering_1,type="l",col ="black" ,xlab="",ylab="Energy sub metering")
lines(data$dateAndTime,data$Sub_metering_2,col ="red")
lines(data$dateAndTime,data$Sub_metering_3,col ="blue")
legend("topright",c("Sub_metering_1","Sub_metering_2","Sub_metering_3"),lty=c(1,1,1),col=c("black","blue","red"), bty="n")
plot(data$dateAndTime,data$Global_reactive_power,type="l",xlab="dateTime",ylab="Global_reactive_power")
dev.off()